Fix pal_crypto_intf.c so can build psa-arch-tests-crypto.
The following provides more information on this commit:
- It's possible to build psa-arch-tests-crypto using a version of
  mbed-crypto off the development branch. However, this doesnt appear
  to have the implementation of the following functions, which
  are required to build psa-arch-tests-crypto:

      ./platform/pal_nspe.a(pal_crypto_intf.c.o): In function `pal_crypto_function':
      pal_crypto_intf.c:(.text+0x1c54): undefined reference to `psa_hash_compute'
      pal_crypto_intf.c:(.text+0x1e6d): undefined reference to `psa_hash_compare'
      pal_crypto_intf.c:(.text+0x2a4b): undefined reference to `psa_aead_encrypt_setup'
      pal_crypto_intf.c:(.text+0x2b8b): undefined reference to `psa_aead_decrypt_setup'
      pal_crypto_intf.c:(.text+0x2d36): undefined reference to `psa_aead_generate_nonce'
      pal_crypto_intf.c:(.text+0x2e7b): undefined reference to `psa_aead_set_nonce'
      pal_crypto_intf.c:(.text+0x2fc0): undefined reference to `psa_aead_set_lengths'
      pal_crypto_intf.c:(.text+0x3105): undefined reference to `psa_aead_update_ad'
      pal_crypto_intf.c:(.text+0x337c): undefined reference to `psa_aead_update'
      pal_crypto_intf.c:(.text+0x3659): undefined reference to `psa_aead_finish'
      pal_crypto_intf.c:(.text+0x38e0): undefined reference to `psa_aead_verify'
      pal_crypto_intf.c:(.text+0x3950): undefined reference to `psa_aead_abort'
      pal_crypto_intf.c:(.text+0x4359): undefined reference to `psa_mac_compute'
      pal_crypto_intf.c:(.text+0x45d5): undefined reference to `psa_mac_verify'
      pal_crypto_intf.c:(.text+0x5a07): undefined reference to `psa_cipher_encrypt'
      pal_crypto_intf.c:(.text+0x5cef): undefined reference to `psa_cipher_decrypt'
      collect2: error: ld returned 1 exit status
      proj_mak:232: recipe for target 'psa-arch-tests-crypto' failed
      make: *** [psa-arch-tests-crypto] Error 1

- To overcome this, the fixes in the file in this commit was added. This will cause
  tests to fail, but it allows ps-arch-tests-crypto to be built.