Fixes to enable build psa-arch-tests-crypto for mbed-crypto testing.
The following provides more information on this commit:
- Fix pal_crypto_intf.c so can build psa-arch-tests-crypto.
  It's possible to build psa-arch-tests-crypto using a version of
  mbed-crypto off the development branch. However, this doesnt appear
  to have the implementation of the following functions, which
  are required to build psa-arch-tests-crypto:

  ./platform/pal_nspe.a(pal_crypto_intf.c.o): In function `pal_crypto_function':
      pal_crypto_intf.c:(...): undefined reference to `psa_hash_compute'
      pal_crypto_intf.c:(...): undefined reference to `psa_hash_compare'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_encrypt_setup'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_decrypt_setup'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_generate_nonce'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_set_nonce'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_set_lengths'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_update_ad'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_update'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_finish'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_verify'
      pal_crypto_intf.c:(...): undefined reference to `psa_aead_abort'
      pal_crypto_intf.c:(...): undefined reference to `psa_mac_compute'
      pal_crypto_intf.c:(...): undefined reference to `psa_mac_verify'
      pal_crypto_intf.c:(...): undefined reference to `psa_cipher_encrypt'
      pal_crypto_intf.c:(...): undefined reference to `psa_cipher_decrypt'
      collect2: error: ld returned 1 exit status
      proj_mak:232: recipe for target 'psa-arch-tests-crypto' failed
      make: *** [psa-arch-tests-crypto] Error 1

- To overcome this, the fixes pal_crypto_intf.c was added. This will cause
  tests to fail, but it allows ps-arch-tests-crypto to be built.
- Additionally, workarounds in test c002, c016 and c050 are included in this
  commit.